In [18]:
import random as rd

rd.seed(1)
rd.random()

0.13436424411240122

In [9]:
rd.randint(10,100)

18

In [17]:
x = list(range(1,9))
rd.choice(x)
rd.shuffle(x)
x

[3, 4, 7, 1, 8, 2, 6, 5]

### Zufällige Matrizen 

In [23]:
import numpy as np

np.round(np.random.rand(3,4))

array([[0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [1., 0., 1., 0.]])

In [26]:
np.random.randint(-99,100, size=(4,10))

array([[ 39,   6,  39,   7,  90,  51,  63, -62,  57, -83],
       [-29, -37,  22,  55,  80,   4, -93,  36,  43, -48],
       [-76, -75, -22, -38, -91,  17,  43, -78,  80, -79],
       [-68,  95,  -4,  52, -79, -75, -44, -48,  47,  94]])

### Spezielle Verteilungen

In [31]:
a,b = 5,10
rd.uniform(a,b)

7.24745532394369

In [33]:
np.random.uniform(a,b, size=(3,5))

array([[9.64189414, 5.15691584, 8.25025495, 6.60184636, 8.77377297],
       [5.79840839, 8.55200707, 6.09701184, 7.23005186, 8.97364485],
       [8.01320973, 7.0976484 , 7.40270879, 7.00954834, 6.95690659]])

In [43]:
lmbd = 10
rd.expovariate(lmbd) # einzele Zahl
np.random.exponential(lmbd, size=(4,4)) # numpy array

array([[11.84650758, 20.88602878, 16.51133102, 13.67150917],
       [ 4.71090444, 12.48560088,  8.291023  ,  8.21717994],
       [ 4.4862538 , 18.41153672,  3.14926712,  5.55968633],
       [ 2.80921219,  6.94210939, 17.52192382,  4.56108829]])

In [45]:
mu, sgm = 50, 5
rd.gauss(mu, sgm) # Normalverteilung

50.02502641813286

In [42]:
np.random.normal(mu, sgm, size=(4,3))

array([[55.20408123, 42.8852291 , 52.36026719],
       [40.88443956, 45.81168785, 50.68000735],
       [51.56503178, 43.0375944 , 47.96533457],
       [61.28700369, 53.73023636, 42.93289946]])

In [44]:
n, p = 50, 0.3
np.random.binomial(n,p,size=(4,10))

array([[14, 17, 20, 14, 16, 14, 18, 16, 10, 17],
       [13, 13, 12, 25, 17, 11, 16, 14, 20, 14],
       [15, 12, 16,  8, 19, 13, 17, 16, 15, 18],
       [19, 11, 11, 15, 18, 25, 14, 23, 16, 15]])

In [46]:
p = 0.2
np.random.geometric(p, size=(4,8))

array([[ 1,  2,  5,  1, 10,  2,  5,  7],
       [ 2,  2, 11, 12,  3,  8,  1,  9],
       [ 1,  2,  3,  4, 11,  5,  8,  4],
       [ 5,  3,  2,  3,  2,  3, 16,  2]])

### Reproduzierbarkeit

In [48]:
# np.random.seed(1)
np.random.normal(10,1,size=(2,4))

array([[10.3190391 ,  9.75062962, 11.46210794,  7.93985929],
       [ 9.6775828 ,  9.61594565, 11.13376944,  8.90010873]])