In [1]:
import numpy as np
import matplotlib.pyplot as plt

#positions of living cells
a = np.array([  [1,0,0,0,0,0,0],
                [1,0,0,0,1,0,0],
                [1,0,1,0,0,1,0],
                [0,0,1,1,0,1,1],
                [0,1,0,1,0,1,1],
                [1,0,1,1,0,0,0]])

showIterations = [0,1,5]

def lnc(i, j, a): #living neighbours
    x = i
    y = j
    neighbours = 0

    """Return neighbours of given cell."""
    cellsToCheck = [(x-1, y-1), (x, y-1),  (x+1, y-1), 
                    (x-1, y),               (x+1, y), 
                    (x-1, y+1), (x, y+1), (x+1, y+1),]
    for x,y in cellsToCheck:
        if x >= 0 and x< a.shape[0] and y >= 0 and y < a.shape[1]:
            # neighbour is alive
            neighbours += a[x, y]
    return int(neighbours)


aneu = np.copy(a)

for its in range(max(showIterations)+1):
    for i in range(a.shape[0]):
        for j in range(a.shape[1]):
            k = lnc(i, j, a)
            if a[i, j] == 0 and k == 3:
                aneu[i, j] = 1
            else:
                if k<2 or k>3:
                    aneu[i, j] = 0
    if its in showIterations:
        print(f"------------ {its}. Generation ------------")
        print(a, end="\n\n")
        print(f"Anzahl lebender Zellen in der 2. Spalte: {a.sum(axis=0)[1]}")
        print(f"Anzahl lebender Zellen in der letzten Zeile: {a.sum(axis=1)[-1]}")
        print(f"Anzahl lebender Zellen insgesamt: {np.sum(a)}", end="\n\n")
    a = np.copy(aneu)

------------ 0. Generation ------------
[[1 0 0 0 0 0 0]
 [1 0 0 0 1 0 0]
 [1 0 1 0 0 1 0]
 [0 0 1 1 0 1 1]
 [0 1 0 1 0 1 1]
 [1 0 1 1 0 0 0]]

Anzahl lebender Zellen in der 2. Spalte: 1
Anzahl lebender Zellen in der letzten Zeile: 3
Anzahl lebender Zellen insgesamt: 17

------------ 1. Generation ------------
[[0 1 0 0 0 0 0]
 [1 0 0 1 0 1 0]
 [0 0 1 0 0 1 1]
 [1 0 1 1 0 1 1]
 [1 1 0 1 0 1 1]
 [0 1 1 1 1 1 1]]

Anzahl lebender Zellen in der 2. Spalte: 3
Anzahl lebender Zellen in der letzten Zeile: 6
Anzahl lebender Zellen insgesamt: 23

------------ 5. Generation ------------
[[0 0 1 1 0 1 0]
 [1 0 1 1 0 1 0]
 [0 0 1 0 1 0 0]
 [1 0 1 1 0 1 1]
 [1 0 0 0 0 0 1]
 [1 1 1 1 1 1 1]]

Anzahl lebender Zellen in der 2. Spalte: 1
Anzahl lebender Zellen in der letzten Zeile: 7
Anzahl lebender Zellen insgesamt: 23

